[project]
name = "wait-for-user-connfirmation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "acontext>=0.0.6",
    "dotenv>=0.9.9",
    "rich>=14.2.0",
]
