[project]
name = "agno-basic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "acontext>=0.0.4",
    "agno>=2.2.13",
    "openai>=2.8.0",
    "python-dotenv>=1.0.0",
]
